version: "3"

networks:
  kong-net:
    driver: bridge
  user-service-net:
    driver: bridge

services:
  # PostgreSQL for Kong
  postgres:
    image: postgres:13
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kongpass
    volumes:
      - kong-data:/var/lib/postgresql/data
    networks:
      - kong-net
    ports:
      - "5432:5432"

  # PostgreSQL for User Service
  user-postgres:
    image: postgres:13
    container_name: user-database
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: user_service
      POSTGRES_PASSWORD: userpass
    volumes:
      - user-data:/var/lib/postgresql/data
    networks:
      - user-service-net
    ports:
      - "5433:5432" # Exposing on a different host port

  # Kong Migrations
  kong-migrations:
    image: kong/kong-gateway:3.9.0.1
    container_name: kong-migrations
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_PASSWORD: test
    networks:
      - kong-net
    depends_on:
      - postgres
    entrypoint: ["/bin/sh", "-c", "kong migrations bootstrap"]
    restart: on-failure

  # Kong Gateway
  kong:
    image: kong/kong-gateway:3.9.0.1
    container_name: kong-gateway
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_LOG_LEVEL: error
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000 http2, 0.0.0.0:8443 http2 ssl
      KONG_ADMIN_GUI_URL: http://localhost:8002
    volumes:
      - ./Protos:/Protos/
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"
    networks:
      - kong-net
    depends_on:
      - kong-migrations
    restart: on-failure

  # RabbitMQ
  rabbit-mq:
    image: rabbitmq:4.0-management
    container_name: rabbit-mq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - user-service-net

volumes:
  kong-data: {}
  user-data: {}
